# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RATapp', '0002_auto_20170322_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
