# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RATapp', '0003_user_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='description',
        ),
    ]
