# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RATapp', '0004_remove_user_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=11, verbose_name='phone'),
        ),
    ]
