# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 21:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RATapp', '0007_auto_20170322_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VIN', models.CharField(default='', max_length=17, verbose_name='VIN')),
                ('number', models.CharField(default='', max_length=9, verbose_name='number')),
                ('brand', models.CharField(default='', max_length=255, verbose_name='brand')),
                ('model', models.CharField(default='', max_length=255, verbose_name='model')),
                ('year', models.CharField(default='', max_length=4, verbose_name='year')),
                ('yeard', models.CharField(default='', max_length=4, verbose_name='yeadddr')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
