# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RATapp', '0008_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='yeard',
        ),
    ]
