# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RATapp', '0010_auto_20170324_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.CharField(default='', max_length=4, verbose_name='yeard'),
        ),
    ]
