# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RATapp', '0013_vehicle_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='user_id',
        ),
    ]
