# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RATapp', '0015_vehicle_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual', models.BooleanField(db_index=True, default=True, verbose_name='is_actual')),
            ],
        ),
        migrations.CreateModel(
            name='CrashDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=24, verbose_name='code')),
                ('description', models.CharField(default='', max_length=255, verbose_name='description')),
            ],
        ),
        migrations.AddField(
            model_name='crash',
            name='description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RATapp.CrashDescription'),
        ),
        migrations.AddField(
            model_name='crash',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RATapp.Vehicle'),
        ),
    ]
