# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RATapp', '0016_auto_20170325_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crash',
            name='actual',
            field=models.BooleanField(db_index=True, default=True, verbose_name='actual'),
        ),
    ]
