# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RATapp', '0019_auto_20170325_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='name')),
                ('description', models.TextField(default='', verbose_name='description')),
                ('address', models.CharField(default='', max_length=100, verbose_name='address')),
                ('phone', models.CharField(default='', max_length=11, verbose_name='phone')),
            ],
        ),
        migrations.RemoveField(
            model_name='crashdescription',
            name='description',
        ),
        migrations.AddField(
            model_name='crashdescription',
            name='full_description',
            field=models.TextField(default='', verbose_name='full_description'),
        ),
        migrations.AddField(
            model_name='crashdescription',
            name='short_description',
            field=models.CharField(default='', max_length=32, verbose_name='short_description'),
        ),
    ]
