# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RATapp', '0022_auto_20170518_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='crash',
        ),
        migrations.AddField(
            model_name='offer',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RATapp.Vehicle'),
        ),
    ]
