# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RATapp', '0023_auto_20170518_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='phone'),
        ),
    ]
