# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RATapp', '0024_auto_20170518_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_auction',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is_auction'),
        ),
    ]
