# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RATapp', '0025_vehicle_is_auction'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='email',
            field=models.TextField(default='', verbose_name='email'),
        ),
    ]
