# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RATapp', '0026_service_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_avalible',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is_avalible'),
        ),
        migrations.AddField(
            model_name='offer',
            name='is_confirmed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is_avalible'),
        ),
    ]
