# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RATapp', '0027_auto_20170519_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='date',
            field=models.TextField(default='', verbose_name='date'),
        ),
    ]
