# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RATapp', '0028_highoffer_lowoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='date',
            field=models.TextField(default='', verbose_name='date'),
        ),
    ]
