# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RATapp', '0028_offer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.TextField(default='', max_length=255, verbose_name='review_date'),
        ),
    ]
