# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RATapp', '0029_auto_20170521_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0, verbose_name='price')),
                ('message', models.TextField(default='', verbose_name='message')),
                ('date', models.TextField(default='', verbose_name='date')),
                ('is_avalible', models.BooleanField(db_index=True, default=False, verbose_name='is_avalible')),
                ('is_confirmed', models.BooleanField(db_index=True, default=False, verbose_name='is_confirmed')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RATapp.Service')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RATapp.Vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='LowOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0, verbose_name='price')),
                ('message', models.TextField(default='', verbose_name='message')),
                ('is_avalible', models.BooleanField(db_index=True, default=False, verbose_name='is_avalible')),
                ('is_chosen', models.BooleanField(db_index=True, default=False, verbose_name='is_chosen')),
                ('crash', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RATapp.Crash')),
                ('high_offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RATapp.HighOffer')),
            ],
        ),
        migrations.AlterField(
            model_name='offer',
            name='is_confirmed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is_confirmed'),
        ),
    ]
