# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RATapp', '0032_user_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highoffer',
            name='message',
        ),
        migrations.RemoveField(
            model_name='highoffer',
            name='price',
        ),
    ]
