# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RATapp', '0033_auto_20170530_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='latitude',
            field=models.FloatField(default=0.0, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='service',
            name='longitude',
            field=models.FloatField(default=0.0, verbose_name='longitude'),
        ),
    ]
