# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RATapp', '0034_auto_20170530_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.TextField(default='', verbose_name='review_date'),
        ),
    ]
